
["Display Properties"]
	# Enable extra absorption rendering when provided by server
	enableAbsorption = true
	# Enable rendering health effects (poison, wither, hardcore) when provided by server
	enableEffects = true
	# ID of mod to render hearts. Ignored if mod is not installed.
	preferredRender = ""

